#!/usr/bin/env python
# SPDX-FileCopyrightText: 2025 Yusaku Washio <s22c1704za@s.chibakoudai.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys


def main() -> int:
    raw_lines = sys.stdin.read().splitlines()

    # 入力なし
    if not raw_lines:
        return 1

    items: list[str] = []

    for line in raw_lines:
        s = line.strip()

        # 空行
        if s == "":
            return 1

        items.append(s)

    # 正常系
    items_sorted = sorted(items)

    print("\n".join(items_sorted))
    return 0


if __name__ == "__main__":
    sys.exit(main())
